name: CI for Pull Requests

on:
  pull_request:
    branches: [main]

env:
  LOCAL_MODEL_URL: "http://localhost:11434/v1"
  LOCAL_MODEL_NAME: "gemma4:latest"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          # Install a specific version of uv.
          version: "0.11.23"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          uv run pytest -v

  agent_evals:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.23"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama and Pull Gemma
        run: |
          ollama serve &
          # Wait for Ollama to be ready
          sleep 5
          ollama pull $LOCAL_MODEL_NAME

      - name: Run agent evals
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          for file in agent/eval*; do
            if [ -f "$file" ]; then
              just_file="${file##*/}"
              filename_without_ext="${just_file%%.*}"
              echo "Running eval for $filename_without_ext"
              uv run python -m agent.$filename_without_ext
            fi
          done
          
