name: CI for Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          # Install a specific version of uv.
          version: "0.11.23"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          uv run pytest -v

  agent_evals:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.23"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama and Pull Gemma
        run: |
          ollama serve &
          # Wait for Ollama to be ready
          sleep 5
          ollama pull gemma4:latest # Choose the size based on runner memory

      - name: Run agent evals
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LOCAL_MODEL_URL: "https://usual-lake-equal.ngrok-free.dev/v1"
          LOCAL_MODEL_NAME: "gemma4:e4b"
        run: uv run python -m agent.agent_eval
